version: "4.61"

services:

  # DataBase
  postgres:
    build:
      context: ../../infrastructure/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
     - maintainer="Mike <kkodokkushi@gmail.com>"
     - version="1.0"
     - description="PostgreSQL 18.2 Server"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-unknown} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
      - ../../infrastructure/postgres/init:/docker-entrypoint-initdb.d

  # DataBase Admin Page
  pgadmin:
    image: dpage/pgadmin4:9.12.0
    restart: unless-stopped
    container_name: pg_admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-unknown}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-unknown}
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  postgres_data:
  pgadmin-data:
